version: '3.8'

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: encurtador-nest-app
    restart: always
    ports:
      - '${PORT:-3333}:${PORT:-3333}'
    depends_on:
      postgres:
        condition: service_healthy
    environment:
      - DATABASE_URL=postgresql://postgres:postgres@postgres:5432/encurtador?schema=public
      - JWT_PRIVATE_KEY=${JWT_PRIVATE_KEY:-secret-jwt-1234}
      - JWT_PUBLIC_KEY=${JWT_PUBLIC_KEY:-secret-jwt-1234}
      - PORT=${PORT:-3333}
      - SHORT_URL_DOMAIN=${SHORT_URL_DOMAIN:-http://localhost:3333}
    volumes:
      - ./:/app
      - /app/node_modules
      - /app/dist
    networks:
      - encurtador-network

  postgres:
    image: postgres:15-alpine
    container_name: encurtador-postgres
    restart: always
    ports:
      - '5432:5432'
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=encurtador
    volumes:
      - postgres-data:/var/lib/postgresql/data
    networks:
      - encurtador-network
    healthcheck:
      test: ['CMD-SHELL', 'pg_isready -U postgres']
      interval: 5s
      timeout: 5s
      retries: 5

networks:
  encurtador-network:
    driver: bridge

volumes:
  postgres-data:
